name       : openal-soft
version    : 1.17.2
release    : 4
source     :
    - http://kcat.strangesoft.net/openal-releases/openal-soft-1.17.2.tar.bz2 : a341f8542f1f0b8c65241a17da13d073f18ec06658e1a1606a8ecc8bbc2b3314
homepage   : http://openal-soft.org/
license    : LGPL-2.1
component  : multimedia.library
summary    : Open Source OpenAL implementation
description: |
    OpenAL Soft is an LGPL-licensed, cross-platform, software implementation of the OpenAL 3D audio API. It's forked from the open-sourced Windows version available originally from openal.org's SVN repository (now defunct).
emul32     : yes
builddeps  :
    - pkgconfig32(alsa)
    - pkgconfig32(libpulse)
    - pkgconfig32(portaudio-2.0)
    - pkgconfig32(sdl2)
    - sdl1-sound-32bit-devel
patterns   :
    - devel : /usr/bin
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %cmake -DLIB_SUFFIX=32 -DCMAKE_INSTALL_PREFIX=/usr .
    else
        %cmake -DLIB_SUFFIX=64 -DCMAKE_INSTALL_PREFIX=/usr .
    fi
build      : |
    %make
install    : |
    %make_install
