name       : openal-soft
version    : 1.18.2
release    : 7
source     :
    - https://github.com/kcat/openal-soft/archive/openal-soft-1.18.2.tar.gz : a598241d1af2e90c25a1b91da4c9ddc0e7cb6a4b5f1477fc680d139c57cd38cc
homepage   : http://openal-soft.org/
license    : LGPL-2.1
component  : multimedia.library
summary    : Open Source OpenAL implementation
description: |
    OpenAL Soft is an LGPL-licensed, cross-platform, software implementation of the OpenAL 3D audio API. It's forked from the open-sourced Windows version available originally from openal.org's SVN repository (now defunct).
emul32     : yes
builddeps  :
    - pkgconfig32(alsa)
    - pkgconfig32(libpulse)
    - pkgconfig32(portaudio-2.0)
    - pkgconfig32(sdl2)
    - sdl1-sound-32bit-devel
patterns   :
    - devel : /usr/bin
setup      : |
    %cmake . -DCMAKE_INSTALL_PREFIX=/usr \
             -DCMAKE_INSTALL_LIBDIR=%libdir%
build      : |
    %make
install    : |
    %make_install
