name        : openal-soft
version     : 1.16.0
release     : 2
source      :
    - http://openal-soft.org/openal-releases/openal-soft-1.16.0.tar.bz2 : 2f3dcd313fe26391284fbf8596863723f99c65d6c6846dccb48e79cadaf40d5f
homepage    : http://openal-soft.org/
license     :
    - LGPL-2.1
summary     : Open Source OpenAL implementation
builddeps   :
    - pkgconfig(libpulse)
    - pkgconfig32(libpulse)
    - pkgconfig(alsa)
    - pkgconfig32(alsa)
    - pkgconfig(sdl2)
    - pkgconfig32(sdl2)
    - glibc-32bit-devel
    - libgcc-32bit
    - libstdc++-32bit
emul32      : yes
patterns    :
    - devel: /usr/bin
description : |
    OpenAL Soft is an LGPL-licensed, cross-platform, software implementation of the OpenAL 3D audio API. It's forked from the open-sourced Windows version available originally from openal.org's SVN repository (now defunct).
setup      : |
    if [[ ! -z "${EMUL32BUILD}" ]]; then
        %cmake -DLIB_SUFFIX=32 -DCMAKE_INSTALL_PREFIX=/usr .
    else
        %cmake -DLIB_SUFFIX=64 -DCMAKE_INSTALL_PREFIX=/usr .
    fi
build      : |
    %make
install    : |
    %make_install
